docs: document how to deploy the forest explorer on a clean CloudFlare account
ChainSafe/forest-explorer pull request #86
Opened 2024-12-06 12:22 UTC by lemmih

## Summary of changes

Changes introduced in this pull request:

- Document the full deployment procedure

## Reference issue to close (if applicable)

Closes #74 

## Other information and links

## Change checklist

- [ ] I have performed a self-review of my own code,
- [ ] I have made corresponding changes to the documentation. All new code
      adheres to the team's
      [documentation standards](https://github.com/ChainSafe/forest/wiki/Documentation-practices),
- [ ] I have added tests that prove my fix is effective or that my feature works
      (if possible),

2024-12-06 15:26 UTC, hanabi1224 submitted a review, later dismissed

2024-12-09 10:41 UTC, sudo-shashank approved these changes

2024-12-09 11:13 UTC, LesnyRumcajs requested changes
1. KV needs to be created manually in CF and modified in the wrangler file.
2. There should be a mention of modifying the routes as well, no?
3. It would be great to change `SECRET_WALLET` to `SECRET_CALIBNET_WALLET` here or in a pre-requisite PR.
4. The pre-requisite of a paid CF plan must be listed - it's not possible  to run this out of the box on a free account.

```
Your worker has access to the following bindings:
- Durable Objects:
  - RATE_LIMITER: RateLimiter

✘ [ERROR] A request to the Cloudflare API (/accounts/fe2fac3a8b68edfa53dc37afa56e26f3/workers/scripts/forest-explorer) failed.

  In order to use Durable Objects, you must switch to a paid plan at
  https://dash.cloudflare.com/fe2fac3a8b68edfa53dc37afa56e26f3/workers/plans [code: 10084]

```
It's possible to work around this by removing the rate limiter, but the steps and the tradeoff should be mentioned.
5. Let's flesh out the steps with some examples.

Otherwise, I managed to deploy it fine on a free account. I'll create a docker file later to encompass the steps above + software pre-requisites so it's possible to one-line deploy. It would help if one would not have to modify the wrangler file and inject the account and others via environment variables.

2025-01-09 11:38 UTC, hanabi1224 submitted a review, later dismissed

2025-01-09 11:40 UTC, LesnyRumcajs approved these changes

2025-01-09 11:57 UTC, hanabi1224 approved these changes

2025-01-09 12:04 UTC, merged